"""initial

Revision ID: 0174af76d98a
Revises: 
Create Date: 2026-03-09 13:45:44.455715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0174af76d98a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bid_id', sa.String(length=64), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=True),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('actor_wallet_id', sa.String(length=255), nullable=True),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_audit_log_bid_id'), 'transaction_audit_log', ['bid_id'], unique=False)
    op.create_index(op.f('ix_transaction_audit_log_property_id'), 'transaction_audit_log', ['property_id'], unique=False)
    op.create_table('transaction_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bid_id', sa.String(length=64), nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'cancelled', 'docs_released', 'docs_confirmed', 'payment_released', 'completed', 'disputed', name='transactionstatusenum'), nullable=False),
    sa.Column('action', sa.Enum('purchase', 'lease', name='transactionactionenum'), nullable=True),
    sa.Column('bid_amount', sa.String(length=64), nullable=True),
    sa.Column('stablecoin_token', sa.String(length=255), nullable=True),
    sa.Column('buyer_wallet_id', sa.String(length=255), nullable=True),
    sa.Column('seller_wallet_id', sa.String(length=255), nullable=True),
    sa.Column('document_token_id', sa.String(length=255), nullable=True),
    sa.Column('escrow_release_tx', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_record_bid_id'), 'transaction_record', ['bid_id'], unique=False)
    op.create_index(op.f('ix_transaction_record_property_id'), 'transaction_record', ['property_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('location', sa.String(length=70), nullable=True),
    sa.Column('account_type', sa.Enum('client', 'agent', 'admin', name='accounttypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_status', sa.Enum('pending', 'verified', 'rejected', name='kycstatusenum'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("account_type IN ('client', 'agent', 'admin')", name='check_account_type'),
    sa.CheckConstraint("kyc_status IN ('pending', 'verified', 'rejected')", name='check_kyc_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'account_type', name='uq_email_type'),
    sa.UniqueConstraint('username', 'account_type', name='uq_username_type')
    )
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('account_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_name', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_token_device_token'), 'device_token', ['device_token'], unique=True)
    op.create_table('wallet_mapping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_mapping_wallet_id'), 'wallet_mapping', ['wallet_id'], unique=True)
    op.create_table('agent_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekdayenum'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('blockchain_property_id', sa.String(), nullable=True),
    sa.Column('transaction_hash', sa.String(), nullable=True),
    sa.Column('is_nft_minted', sa.Boolean(), nullable=True),
    sa.Column('blockchain_owner_id', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=70), nullable=False),
    sa.Column('property_type', sa.Enum('apartment', 'land', 'shortlet', 'shared_apartment', name='propertytypeenum'), nullable=False),
    sa.Column('listing_type', sa.Enum('rent', 'sale', name='listingtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('available', 'sold', 'rented', name='propertystatenum'), nullable=False),
    sa.Column('furnished', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bathroom', sa.Integer(), nullable=False),
    sa.Column('bedroom', sa.Integer(), nullable=False),
    sa.Column('air_condition', sa.Boolean(), nullable=False),
    sa.Column('pop_ceiling', sa.Boolean(), nullable=False),
    sa.Column('floor_tiles', sa.Boolean(), nullable=False),
    sa.Column('running_water', sa.Boolean(), nullable=False),
    sa.Column('furniture', sa.Boolean(), nullable=False),
    sa.Column('prepaid_meter', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.CheckConstraint("listing_type IN ('rent', 'sale')", name='check_listing'),
    sa.CheckConstraint("property_type IN ('apartment', 'land', 'shortlet', 'shared_apartment')", name='check_property_type'),
    sa.CheckConstraint("status IN ('available', 'sold', 'rented')", name='check_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('ratee_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ratee_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', name='appointmentstatenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_at')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.Enum('rent', 'sale', name='listingtypeenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_index(op.f('ix_contract_idempotency_key'), 'contract', ['idempotency_key'], unique=True)
    op.create_table('minted_property_draft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blockchain_property_id', sa.String(length=64), nullable=False),
    sa.Column('owner_wallet_id', sa.String(length=255), nullable=False),
    sa.Column('metadata_uri', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('linked_property_id', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_property_id'], ['property.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blockchain_property_id')
    )
    op.create_table('property_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.Enum('bid_accepted', 'bid_rejected', 'docs_released', 'docs_confirmed', 'payment_released', name='transactioneventenum'), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_notification_transaction_id'), 'transaction_notification', ['transaction_id'], unique=False)
    op.create_table('payment_confirmation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_confirmation_idempotency_key'), 'payment_confirmation', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_confirmation_idempotency_key'), table_name='payment_confirmation')
    op.drop_table('payment_confirmation')
    op.drop_index(op.f('ix_transaction_notification_transaction_id'), table_name='transaction_notification')
    op.drop_table('transaction_notification')
    op.drop_table('property_image')
    op.drop_table('minted_property_draft')
    op.drop_index(op.f('ix_contract_idempotency_key'), table_name='contract')
    op.drop_table('contract')
    op.drop_table('chat_message')
    op.drop_table('appointment')
    op.drop_table('rating')
    op.drop_table('property')
    op.drop_table('agent_availability')
    op.drop_index(op.f('ix_wallet_mapping_wallet_id'), table_name='wallet_mapping')
    op.drop_table('wallet_mapping')
    op.drop_index(op.f('ix_device_token_device_token'), table_name='device_token')
    op.drop_table('device_token')
    op.drop_table('client')
    op.drop_table('agent')
    op.drop_table('admin')
    op.drop_table('account_info')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_transaction_record_property_id'), table_name='transaction_record')
    op.drop_index(op.f('ix_transaction_record_bid_id'), table_name='transaction_record')
    op.drop_table('transaction_record')
    op.drop_index(op.f('ix_transaction_audit_log_property_id'), table_name='transaction_audit_log')
    op.drop_index(op.f('ix_transaction_audit_log_bid_id'), table_name='transaction_audit_log')
    op.drop_table('transaction_audit_log')
    # ### end Alembic commands ###
