"""added txn hash, mint attr, owner id

Revision ID: 0292f636c71d
Revises: 4f1b9e0c7d2a
Create Date: 2026-02-16 14:48:43.350214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0292f636c71d'
down_revision: Union[str, Sequence[str], None] = '4f1b9e0c7d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_token_device_token'))
        batch_op.create_index(batch_op.f('ix_device_token_device_token'), ['device_token'], unique=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_nft_minted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('blockchain_owner_id', sa.String(), nullable=True))

    with op.batch_alter_table('transaction_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_audit_log_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('wallet_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_mapping_wallet_id'))
        batch_op.create_index(batch_op.f('ix_wallet_mapping_wallet_id'), ['wallet_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_mapping_wallet_id'))
        batch_op.create_index(batch_op.f('ix_wallet_mapping_wallet_id'), ['wallet_id'], unique=False)

    with op.batch_alter_table('transaction_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_audit_log_property_id'))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('blockchain_owner_id')
        batch_op.drop_column('is_nft_minted')
        batch_op.drop_column('transaction_hash')

    with op.batch_alter_table('device_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_token_device_token'))
        batch_op.create_index(batch_op.f('ix_device_token_device_token'), ['device_token'], unique=False)

    # ### end Alembic commands ###
