"""added new field

Revision ID: 5feae988a652
Revises: 0292f636c71d
Create Date: 2026-02-18 09:37:12.863356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5feae988a652'
down_revision: Union[str, Sequence[str], None] = '0292f636c71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_contract_idempotency_key'), ['idempotency_key'], unique=True)

    with op.batch_alter_table('payment_confirmation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_confirmation_idempotency_key'), ['idempotency_key'], unique=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('is_nft_minted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('is_nft_minted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('payment_confirmation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_confirmation_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
